version = 1

[[annotations]]
path = [".github/PULL_REQUEST_TEMPLATE.md",".cache/**","REUSE.toml", "ci/**","artifacts/**", "VERSION", "go.sum", "**.json", "venv-env/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
