# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["VERSION", "**/go.sum", "venv-env", "vendor"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
