// Package openpolicyagent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openpolicyagent

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostV1DataPackageRuleWithBody request with any body
	PostV1DataPackageRuleWithBody(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1DataPackageRule(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, body PostV1DataPackageRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostV1DataPackageRuleWithBody(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1DataPackageRuleRequestWithBody(c.Server, pPackage, rule, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1DataPackageRule(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, body PostV1DataPackageRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1DataPackageRuleRequest(c.Server, pPackage, rule, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostV1DataPackageRuleRequest calls the generic PostV1DataPackageRule builder with application/json body
func NewPostV1DataPackageRuleRequest(server string, pPackage string, rule string, params *PostV1DataPackageRuleParams, body PostV1DataPackageRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1DataPackageRuleRequestWithBody(server, pPackage, rule, params, "application/json", bodyReader)
}

// NewPostV1DataPackageRuleRequestWithBody generates requests for PostV1DataPackageRule with any type of body
func NewPostV1DataPackageRuleRequestWithBody(server string, pPackage string, rule string, params *PostV1DataPackageRuleParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "rule", runtime.ParamLocationPath, rule)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/data/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Explain != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "explain", runtime.ParamLocationQuery, *params.Explain); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Pretty != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pretty", runtime.ParamLocationQuery, *params.Pretty); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Metrics != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "metrics", runtime.ParamLocationQuery, *params.Metrics); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Provenance != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "provenance", runtime.ParamLocationQuery, *params.Provenance); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostV1DataPackageRuleWithBodyWithResponse request with any body
	PostV1DataPackageRuleWithBodyWithResponse(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1DataPackageRuleResponse, error)

	PostV1DataPackageRuleWithResponse(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, body PostV1DataPackageRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1DataPackageRuleResponse, error)
}

type PostV1DataPackageRuleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OpaResponse
	JSONDefault  *OpaError
}

// Status returns HTTPResponse.Status
func (r PostV1DataPackageRuleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1DataPackageRuleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostV1DataPackageRuleWithBodyWithResponse request with arbitrary body returning *PostV1DataPackageRuleResponse
func (c *ClientWithResponses) PostV1DataPackageRuleWithBodyWithResponse(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1DataPackageRuleResponse, error) {
	rsp, err := c.PostV1DataPackageRuleWithBody(ctx, pPackage, rule, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1DataPackageRuleResponse(rsp)
}

func (c *ClientWithResponses) PostV1DataPackageRuleWithResponse(ctx context.Context, pPackage string, rule string, params *PostV1DataPackageRuleParams, body PostV1DataPackageRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1DataPackageRuleResponse, error) {
	rsp, err := c.PostV1DataPackageRule(ctx, pPackage, rule, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1DataPackageRuleResponse(rsp)
}

// ParsePostV1DataPackageRuleResponse parses an HTTP response from a PostV1DataPackageRuleWithResponse call
func ParsePostV1DataPackageRuleResponse(rsp *http.Response) (*PostV1DataPackageRuleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1DataPackageRuleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OpaResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest OpaError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
