// Package openidconnect provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openidconnect

// Defines values for TokenGrantType.
const (
	AuthorizationCode                        TokenGrantType = "authorization_code"
	ClientCredentials                        TokenGrantType = "client_credentials"
	Password                                 TokenGrantType = "password"
	RefreshToken                             TokenGrantType = "refresh_token"
	UrnIetfParamsOauthGrantTypeDeviceCode    TokenGrantType = "urn:ietf:params:oauth:grant-type:device_code"
	UrnIetfParamsOauthGrantTypeSaml2Bearer   TokenGrantType = "urn:ietf:params:oauth:grant-type:saml2-bearer"
	UrnIetfParamsOauthGrantTypeTokenExchange TokenGrantType = "urn:ietf:params:oauth:grant-type:token-exchange"
	UrnOpenidParamsGrantTypeCiba             TokenGrantType = "urn:openid:params:grant-type:ciba"
)

// Defines values for TokenErrorError.
const (
	InvalidClient        TokenErrorError = "invalid_client"
	InvalidGrant         TokenErrorError = "invalid_grant"
	InvalidRequest       TokenErrorError = "invalid_request"
	InvalidScope         TokenErrorError = "invalid_scope"
	UnsupportedGrantType TokenErrorError = "unsupported_grant_type"
)

// MTLSEndpointAliases MTLS Endpoint Aliases
type MTLSEndpointAliases struct {
	// BackchannelAuthenticationEndpoint Backchannel Authorization Endpoint
	BackchannelAuthenticationEndpoint *string `json:"backchannel_authentication_endpoint,omitempty"`

	// DeviceAuthorizationEndpoint Device Authorization Endpoint
	DeviceAuthorizationEndpoint *string `json:"device_authorization_endpoint,omitempty"`

	// IntrospectionEndpoint Introspection Endpoint
	IntrospectionEndpoint *string `json:"introspection_endpoint,omitempty"`

	// PushedAuthorizationRequestEndpoint Pushed Authorization Request Endpoint
	PushedAuthorizationRequestEndpoint *string `json:"pushed_authorization_request_endpoint,omitempty"`

	// RegistrationEndpoint Registration Endpoint
	RegistrationEndpoint *string `json:"registration_endpoint,omitempty"`

	// RevocationEndpoint Revocation Endpoint
	RevocationEndpoint *string `json:"revocation_endpoint,omitempty"`

	// TokenEndpoint Token Endpoint
	TokenEndpoint *string `json:"token_endpoint,omitempty"`

	// UserinfoEndpoint Userinfo Endpoint
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`
}

// Token defines model for Token.
type Token struct {
	// Claims A comma delimited list of claims required
	Claims *string `json:"claims,omitempty"`

	// ClientId Obtained during either manual client registration or through the Dynamic Client Registration API. It identifies the client and must match the value preregistered in Keycloak.
	ClientId *string `json:"client_id,omitempty"`

	// Code Required if grant_type is authorization_code. The value is what was returned from the authorization endpoint. The code has a lifetime of 300 seconds
	Code *string `json:"code,omitempty"`

	// CodeVerifier Required if grant_type is authorization_code and code_challenge was specified in the original /authorize request. This value is the code verifier for PKCE. Okta uses it to recompute the code_challenge and verify if it matches the original code_challenge in the authorization request.
	CodeVerifier *string         `json:"code_verifier,omitempty"`
	GrantType    *TokenGrantType `json:"grant_type,omitempty"`

	// Password Required if the grant_type is password.
	Password *string `json:"password,omitempty"`

	// RedirectUri Required if grant_type is authorization_code. Specifies the callback location where the authorization was sent. This value must match the redirect_uri used to generate the original authorization_code.
	RedirectUri *string `json:"redirect_uri,omitempty"`

	// RefreshToken Required if grant_type is refresh_token. The value is a valid refresh token that was returned from this endpoint previously.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope Required if password is the grant_type. This is a list of scopes that the client wants to be included in the access token. For the refresh_token grant type, these scopes have to be a subset of the scopes used to generate the refresh token in the first place.
	Scope *string `json:"scope,omitempty"`

	// Username Required if the grant_type is password.
	Username *string `json:"username,omitempty"`
}

// TokenGrantType defines model for Token.GrantType.
type TokenGrantType string

// TokenError defines model for TokenError.
type TokenError struct {
	Error            *TokenErrorError `json:"error,omitempty"`
	ErrorDescription *string          `json:"error_description,omitempty"`
}

// TokenErrorError defines model for TokenError.Error.
type TokenErrorError string

// TokenResponse Based on the scopes requested. Generally speaking, the scopes specified in a request are included in the access token in the response.
type TokenResponse struct {
	// AccessToken An access token.
	AccessToken *string `json:"access_token,omitempty"`

	// DeviceSecret An opaque device secret. This is returned if the device_sso scope is granted.
	DeviceSecret *string `json:"device_secret,omitempty"`

	// ExpiresIn The expiration time of the access token in seconds.
	ExpiresIn *int `json:"expires_in,omitempty"`

	// IdToken An ID token. This is returned if the openid scope is granted.
	IdToken *string `json:"id_token,omitempty"`

	// RefreshExpiresIn The expiration time of the refresh token in seconds.
	RefreshExpiresIn *int `json:"refresh_expires_in,omitempty"`

	// RefreshToken An opaque refresh token. This is returned if the offline_access scope is granted.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope The scopes contained in the access token.
	Scope *string `json:"scope,omitempty"`

	// TokenType The audience of the token.
	TokenType *string `json:"token_type,omitempty"`
}

// WellKnownResponse Publicly available resource that gives paths to other resources.
type WellKnownResponse struct {
	// AcrValuesSupported ACR Values Supported
	AcrValuesSupported *[]string `json:"acr_values_supported,omitempty"`

	// AuthorizationEncryptionAlgValuesSupported Authorization Encryption Alg Values Supported
	AuthorizationEncryptionAlgValuesSupported *[]string `json:"authorization_encryption_alg_values_supported,omitempty"`

	// AuthorizationEncryptionEncValuesSupported Authorization Encryption Enc Values Supported
	AuthorizationEncryptionEncValuesSupported *[]string `json:"authorization_encryption_enc_values_supported,omitempty"`

	// AuthorizationEndpoint Authorization Endpoint URL
	AuthorizationEndpoint *string `json:"authorization_endpoint,omitempty"`

	// AuthorizationSigningAlgValuesSupported Authorization Signing Alg Values Supported
	AuthorizationSigningAlgValuesSupported *[]string `json:"authorization_signing_alg_values_supported,omitempty"`

	// BackchannelAuthenticationEndpoint Backchannel Authentication Endpoint
	BackchannelAuthenticationEndpoint *string `json:"backchannel_authentication_endpoint,omitempty"`

	// BackchannelAuthenticationRequestSigningAlgValuesSupported Backchannel Authentication Request Signing Alg Values Supported
	BackchannelAuthenticationRequestSigningAlgValuesSupported *[]string `json:"backchannel_authentication_request_signing_alg_values_supported,omitempty"`

	// BackchannelLogoutSessionSupported Backchannel Logout Session Supported
	BackchannelLogoutSessionSupported *bool `json:"backchannel_logout_session_supported,omitempty"`

	// BackchannelLogoutSupported Backchannel Logout Supported
	BackchannelLogoutSupported *bool `json:"backchannel_logout_supported,omitempty"`

	// BackchannelTokenDeliveryModesSupported Backchannel Token Delivery Methods Supported
	BackchannelTokenDeliveryModesSupported *[]string `json:"backchannel_token_delivery_modes_supported,omitempty"`

	// CheckSessionIframe Check Session iFrame URL
	CheckSessionIframe *string `json:"check_session_iframe,omitempty"`

	// ClaimTypesSupported Claim Types Supported
	ClaimTypesSupported *[]string `json:"claim_types_supported,omitempty"`

	// ClaimsParameterSupported Claims Parameter Supported
	ClaimsParameterSupported *bool `json:"claims_parameter_supported,omitempty"`

	// ClaimsSupported Claims Supported
	ClaimsSupported *[]string `json:"claims_supported,omitempty"`

	// CodeChallengeMethodsSupported Code Challenge Methods Supported
	CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported,omitempty"`

	// DeviceAuthorizationEndpoint Device Authorization Endpoint
	DeviceAuthorizationEndpoint *string `json:"device_authorization_endpoint,omitempty"`

	// EndSessionEndpoint Endsession Endpoint URL
	EndSessionEndpoint *string `json:"end_session_endpoint,omitempty"`

	// FrontchannelLogoutSessionSupported Frontchannel Logout Session Supported
	FrontchannelLogoutSessionSupported *bool `json:"frontchannel_logout_session_supported,omitempty"`

	// FrontchannelLogoutSupported Frontchannel Logout Supported
	FrontchannelLogoutSupported *bool `json:"frontchannel_logout_supported,omitempty"`

	// GrantTypesSupported Grant Types Supported
	GrantTypesSupported *[]string `json:"grant_types_supported,omitempty"`

	// IdTokenEncryptionAlgValuesSupported ID Token encryption alg values Supported
	IdTokenEncryptionAlgValuesSupported *[]string `json:"id_token_encryption_alg_values_supported,omitempty"`

	// IdTokenEncryptionEncValuesSupported ID Token encryption enc values Supported
	IdTokenEncryptionEncValuesSupported *[]string `json:"id_token_encryption_enc_values_supported,omitempty"`

	// IdTokenSigningAlgValuesSupported ID Token signing alg values Supported
	IdTokenSigningAlgValuesSupported *[]string `json:"id_token_signing_alg_values_supported,omitempty"`

	// IntrospectionEndpoint Introspection Endpoint URL
	IntrospectionEndpoint *string `json:"introspection_endpoint,omitempty"`

	// IntrospectionEndpointAuthMethodsSupported Introspection Endpoint Auth Methods Supported
	IntrospectionEndpointAuthMethodsSupported *[]string `json:"introspection_endpoint_auth_methods_supported,omitempty"`

	// IntrospectionEndpointAuthSigningAlgValuesSupported Introspection Endpoint Auth Signing Alg Values Supported
	IntrospectionEndpointAuthSigningAlgValuesSupported *[]string `json:"introspection_endpoint_auth_signing_alg_values_supported,omitempty"`

	// Issuer Issuer URL
	Issuer *string `json:"issuer,omitempty"`

	// JwksUri JWKS URI
	JwksUri *string `json:"jwks_uri,omitempty"`

	// MtlsEndpointAliases MTLS Endpoint Aliases
	MtlsEndpointAliases *MTLSEndpointAliases `json:"mtls_endpoint_aliases,omitempty"`

	// PushedAuthorizationRequestEndpoint Pushed Authorization Request Endpoint
	PushedAuthorizationRequestEndpoint *string `json:"pushed_authorization_request_endpoint,omitempty"`

	// RegistrationEndpoint Registration Endpoint URL
	RegistrationEndpoint *string `json:"registration_endpoint,omitempty"`

	// RequestObjectEncryptionAlgValuesSupported Request Object Encryption alg values Supported
	RequestObjectEncryptionAlgValuesSupported *[]string `json:"request_object_encryption_alg_values_supported,omitempty"`

	// RequestObjectEncryptionEncValuesSupported Request Object Encryption enc values Supported
	RequestObjectEncryptionEncValuesSupported *[]string `json:"request_object_encryption_enc_values_supported,omitempty"`

	// RequestObjectSigningAlgValuesSupported Request Object Signing alg values Supported
	RequestObjectSigningAlgValuesSupported *[]string `json:"request_object_signing_alg_values_supported,omitempty"`

	// RequestParameterSupported Request Parameter Supported
	RequestParameterSupported *bool `json:"request_parameter_supported,omitempty"`

	// RequestUriParameterSupported Request URI Parameter Supported
	RequestUriParameterSupported *bool `json:"request_uri_parameter_supported,omitempty"`

	// RequirePushedAuthorizationRequests Require Pushed Authorization Requests
	RequirePushedAuthorizationRequests *bool `json:"require_pushed_authorization_requests,omitempty"`

	// RequireRequestUriRegistration Require Request URI Registration
	RequireRequestUriRegistration *bool `json:"require_request_uri_registration,omitempty"`

	// ResponseModesSupported Response Modes Supported
	ResponseModesSupported *[]string `json:"response_modes_supported,omitempty"`

	// ResponseTypesSupported Response Types Supported
	ResponseTypesSupported *[]string `json:"response_types_supported,omitempty"`

	// RevocationEndpoint Revocation Endpoint URL
	RevocationEndpoint *string `json:"revocation_endpoint,omitempty"`

	// RevocationEndpointAuthMethodsSupported Revocation Endpoint Auth Methods Supported
	RevocationEndpointAuthMethodsSupported *[]string `json:"revocation_endpoint_auth_methods_supported,omitempty"`

	// RevocationEndpointAuthSigningAlgValuesSupported Revocation Endpoint Auth Signing Alg Values Supported
	RevocationEndpointAuthSigningAlgValuesSupported *[]string `json:"revocation_endpoint_auth_signing_alg_values_supported,omitempty"`

	// ScopesSupported Scopes Types Supported
	ScopesSupported *[]string `json:"scopes_supported,omitempty"`

	// SubjectTypesSupported Subject Types Supported
	SubjectTypesSupported *[]string `json:"subject_types_supported,omitempty"`

	// TlsClientCertificateBoundAccessTokens TLS Client Certificate Bound Access Tokens
	TlsClientCertificateBoundAccessTokens *bool `json:"tls_client_certificate_bound_access_tokens,omitempty"`

	// TokenEndpoint Token Endpoint URL
	TokenEndpoint *string `json:"token_endpoint,omitempty"`

	// TokenEndpointAuthMethodsSupported Token Endpoint Auth Methods Supported
	TokenEndpointAuthMethodsSupported *[]string `json:"token_endpoint_auth_methods_supported,omitempty"`

	// TokenEndpointAuthSigningAlgValuesSupported Token Endpoint Auth Signing Alg Values Supported
	TokenEndpointAuthSigningAlgValuesSupported *[]string `json:"token_endpoint_auth_signing_alg_values_supported,omitempty"`

	// UserinfoEncryptionAlgValuesSupported UserInfo Encryption alg values Supported
	UserinfoEncryptionAlgValuesSupported *[]string `json:"userinfo_encryption_alg_values_supported,omitempty"`

	// UserinfoEncryptionEncValuesSupported UserInfo Encryption enc values Supported
	UserinfoEncryptionEncValuesSupported *[]string `json:"userinfo_encryption_enc_values_supported,omitempty"`

	// UserinfoEndpoint Userinfo Endpoint URL
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`

	// UserinfoSigningAlgValuesSupported UserInfo Signing alg values Supported
	UserinfoSigningAlgValuesSupported *[]string `json:"userinfo_signing_alg_values_supported,omitempty"`
}

// PostProtocolOpenidConnectTokenFormdataRequestBody defines body for PostProtocolOpenidConnectToken for application/x-www-form-urlencoded ContentType.
type PostProtocolOpenidConnectTokenFormdataRequestBody = Token
