---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Auto Update PR

# On push to the main branch and support branches, update any branches that are out of date
# and have auto-merge enabled. If the branch is currently out of date with the base branch,
# it must be first manually updated and then will be kept up to date on future runs.
on:
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Auto-Update-PR:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - uses: tibdex/auto-update@v2.2.1
        with:
          github_token: ${{ secrets.SYS_ORCH_GITHUB }}