---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_version_check: true
      run_dep_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_helm_build: false
      run_helm_push: false
      run_version_tag: true
      run_artifact: false
      prefix_tag_separator: "/"
      project_folder: "go/dazl/zap"
    secrets: inherit
