---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Scorecard CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-scorecard:
    permissions:
      security-events: write   # required for SARIF upload
      id-token: write
      contents: read

    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@c36d5c7be1b1bf1913a53fcf2c320b0423beae92  # 2026.1.1
    with:
      project_folder: "."
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
